spring:
  application:
    name: gateway
  config:
    import:
      - optional:classpath:application-common.yaml
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: order-route
              uri: lb://order
              predicates:
                - Path=/api/order/**
              filters:
                - RewritePath=/api/(?<segment>.*),/$\{segment}
            - id: coupon-route
              uri: lb://coupon
              predicates:
                - Path=/api/coupon/**
              filters:
                - RewritePath=/api/(?<segment>.*),/$\{segment}
            - id: product-route
              uri: lb://product
              predicates:
                - Path=/api/product/**
              filters:
                - RewritePath=/api/(?<segment>.*),/$\{segment}
            - id: member-route
              uri: lb://member
              predicates:
                - Path=/api/member/**
              filters:
                - RewritePath=/api/(?<segment>.*),/$\{segment}
            - id: ware-route
              uri: lb://ware
              predicates:
                - Path=/api/ware/**
              filters:
                - RewritePath=/api/(?<segment>.*),/$\{segment}
            - id: third-party-route
              uri: lb://third-party
              predicates:
                - Path=/api/thirdParty/**
              filters:
                - RewritePath=/api/(?<segment>.*),/$\{segment}
            - id: admin-route
              uri: lb://renren-fast
              predicates:
                - Path=/api/**
              filters:
                - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
            - id: host-route
              uri: lb://product
              predicates:
                - Host=gulimall.com
            - id: search-route
              uri: lb://search
              predicates:
                - Host=search.gulimall.com
            - id: item-route
              uri: lb://product
              predicates:
                - Host=item.gulimall.com
            - id: auth_route
              uri: lb://auth
              predicates:
                - Host=auth.gulimall.com
            - id: cart_route
              uri: lb://cart
              predicates:
                - Host=cart.gulimall.com
            - id: order_route
              uri: lb://order
              predicates:
                - Host=order.gulimall.com
            - id: member_route
              uri: lb://member
              predicates:
                - Host=member.gulimall.com
            - id: seckill_route
              uri: lb://seckill
              predicates:
                - Host=seckill.gulimall.com

server:
  port: 53000