spring:
  application:
    name: gateway
  config:
    import:
      - optional:classpath:application-common.yaml
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: product-route
              uri: lb://product
              predicates:
                - Path=/api/product/**
              filters:
                - RewritePath=/api/(?<segment>.*),/$\{segment}
            - id: admin-route
              uri: lb://renren-fast
              predicates:
                - Path=/api/**
              filters:
                - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

server:
  port: 53000