spring:
  config:
    import:
      - optional:classpath:args.yaml
      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}?group=${spring.cloud.nacos.config.group}
  datasource:
    username: ${MYSQL-USERNAME}
    password: ${MYSQL-PASSWORD}
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL-URL}:${MYSQL-PORT}/${spring.datasource.name}
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password}
      dataBase: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 5000ms
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      key-prefix: "cache:"
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS-URL}:${NACOS-PORT}
      config:
        server-addr: ${NACOS-URL}:${NACOS-PORT}
        file-extension: yaml
        group: gulimall
        namespace: gulimall
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
  session:
    redis:
      namespace: session
      flush-mode: on_save
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0
      logic-not-delete-value: 1
server:
  servlet:
    session:
      timeout: 10d